/*
 * generated by Xtext
 */
package fr.lip6.move.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class TimedAutomataUiModule extends AbstractTimedAutomataUiModule {
}
