/*
 * generated by Xtext 2.33.0
 */
package fr.lip6.move.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class AhgUiModule extends AbstractAhgUiModule {

	public AhgUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
