/*
* generated by Xtext
*/
package fr.lip6.move;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TimedAutomataStandaloneSetup extends TimedAutomataStandaloneSetupGenerated{

	public static void doSetup() {
		new TimedAutomataStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

