/*
 * generated by Xtext
 */
package fr.lip6.move


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TimedAutomataRuntimeModule extends AbstractTimedAutomataRuntimeModule {
}
