<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="promela" nsURI="http://www.lip6.fr/move/promela/Promela" nsPrefix="promela">
  <eClassifiers xsi:type="ecore:EClass" name="PromelaSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="macros" upperBound="-1"
        eType="#//DefineMacro" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mtypes" upperBound="-1"
        eType="#//MTypeDef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userTypes" upperBound="-1"
        eType="#//TypeDef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalVariables" upperBound="-1"
        eType="#//VariableDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processes" upperBound="-1"
        eType="#//ProcessDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="InitProcess" eSuperTypes="#//ProcessDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="corps" upperBound="-1"
        eType="#//Sequence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedProcess" eSuperTypes="#//ProcessDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="active" eType="#//Active"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parametres" upperBound="-1"
        eType="#//VariableDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="priority" eType="#//Priority"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contrainte" eType="#//Constraint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="corps" eType="#//Sequence"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Active">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activeVal" eType="#//AtomicInt"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Priority">
    <eStructuralFeatures xsi:type="ecore:EReference" name="level" eType="#//AtomicInt"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Run" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="process" eType="#//NamedProcess"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" upperBound="-1"
        eType="#//Step" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Step"/>
  <eClassifiers xsi:type="ecore:EClass" name="Instruction" eSuperTypes="#//Step"/>
  <eClassifiers xsi:type="ecore:EClass" name="LabeledInstruction" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instruction" eType="#//Instruction"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabeledAtomic" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instruction" eType="#//Instruction"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalBlock" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="corps" upperBound="-1"
        eType="#//Sequence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Selection" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" upperBound="-1"
        eType="#//Sequence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//Sequence"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Iteration" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" upperBound="-1"
        eType="#//Sequence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//Sequence"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="For" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" eType="#//Reference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="min" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="max" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="array" eType="#//Reference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="corps" eType="#//Sequence"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Skip" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Break" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Goto" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" eType="#//LabeledInstruction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicSequence" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="corps" eType="#//Sequence"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeterministicAtomicSequence" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="corps" eType="#//Sequence"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assert" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Print" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclaration" eSuperTypes="#//Step #//Referable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Referable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicVariable" eSuperTypes="#//VariableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//BasicType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initValue" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructVariable" eSuperTypes="#//VariableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//StructTypeRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TabVariable" eSuperTypes="#//VariableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="length" eType="#//AtomicInt"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initValue" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefineMacro"/>
  <eClassifiers xsi:type="ecore:EClass" name="DefineIntMacro" eSuperTypes="#//Referable #//DefineMacro">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" eSuperTypes="#//ReceiveArg #//Expression #//AtomicInt #//Poll">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//Referable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targets" upperBound="-1"
        eType="#//RefTarget" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefTarget"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChanVariable" eSuperTypes="#//VariableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initValue" eType="#//ChanInitialize"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChanInitialize">
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" eType="#//AtomicInt"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SendArgs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Eval" eSuperTypes="#//ReceiveArg">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CapacityPoll" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//ChanPollOperators"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="channel" eType="#//Reference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ChanPollOperators">
    <eLiterals name="FULL" literal="full"/>
    <eLiterals name="EMPTY" value="1" literal="empty"/>
    <eLiterals name="NFULL" value="2" literal="nfull"/>
    <eLiterals name="NEMPTY" value="3" literal="nempty"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Length" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="channel" eType="#//Reference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReceiveArgs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="recArgs" upperBound="-1"
        eType="#//ReceiveArg" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReceiveArg"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChannelExclusiveAssertion" eSuperTypes="#//Step">
    <eStructuralFeatures xsi:type="ecore:EReference" name="channel" eType="#//Reference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="MTypeDef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="messages" upperBound="-1"
        eType="#//MTypeSymbol" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MTypeSymbol" eSuperTypes="#//Referable"/>
  <eClassifiers xsi:type="ecore:EClass" name="StructTypeRef" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//TypeDef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="champs" upperBound="-1"
        eType="#//StructField" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructField">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Select" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" eType="#//Reference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="min" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="max" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="#//Constraint #//Instruction #//Send #//Receive #//Assignement"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ComparisonOperators">
    <eLiterals name="GT" literal=">"/>
    <eLiterals name="LT" value="1" literal="&lt;"/>
    <eLiterals name="GE" value="2" literal=">="/>
    <eLiterals name="LE" value="3" literal="&lt;="/>
    <eLiterals name="EQ" value="4" literal="=="/>
    <eLiterals name="NE" value="5" literal="!="/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WrapExpr" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicInt" eSuperTypes="#//ReceiveArg"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralConstant" eSuperTypes="#//Expression #//AtomicInt">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="True" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="False" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Timeout" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Send"/>
  <eClassifiers xsi:type="ecore:EClass" name="Receive"/>
  <eClassifiers xsi:type="ecore:EClass" name="Assignement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Poll"/>
  <eClassifiers xsi:type="ecore:EClass" name="FifoSend" eSuperTypes="#//Instruction #//Send">
    <eStructuralFeatures xsi:type="ecore:EReference" name="channel" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" eType="#//SendArgs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SortedSend" eSuperTypes="#//Instruction #//Send">
    <eStructuralFeatures xsi:type="ecore:EReference" name="channel" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" eType="#//SendArgs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NormalReceive" eSuperTypes="#//Instruction #//Receive">
    <eStructuralFeatures xsi:type="ecore:EReference" name="channel" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" eType="#//ReceiveArgs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RandomReceive" eSuperTypes="#//Instruction #//Receive">
    <eStructuralFeatures xsi:type="ecore:EReference" name="channel" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" eType="#//ReceiveArgs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NormalReceiveKeep" eSuperTypes="#//Instruction #//Receive">
    <eStructuralFeatures xsi:type="ecore:EReference" name="channel" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" eType="#//ReceiveArgs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RandomReceiveKeep" eSuperTypes="#//Instruction #//Receive">
    <eStructuralFeatures xsi:type="ecore:EReference" name="channel" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" eType="#//ReceiveArgs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StandardAssignment" eSuperTypes="#//Instruction #//Assignement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newValue" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DecrementAssignment" eSuperTypes="#//Instruction #//Assignement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IncrementAssignment" eSuperTypes="#//Instruction #//Assignement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Printf" eSuperTypes="#//Print">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="chaine" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Printm" eSuperTypes="#//Print">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TabRef" eSuperTypes="#//RefTarget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructRef" eSuperTypes="#//RefTarget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="field" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExclusiveSendAssertion" eSuperTypes="#//ChannelExclusiveAssertion"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExclusiveReceiveAssertion" eSuperTypes="#//ChannelExclusiveAssertion"/>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Not" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comparison" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//ComparisonOperators"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Operatorsright" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryIntExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BitComplement" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryMinus" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CasualExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//WrapExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="consequence" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alternative" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NormalPoll" eSuperTypes="#//Expression #//Poll">
    <eStructuralFeatures xsi:type="ecore:EReference" name="channel" eType="#//Reference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" eType="#//ReceiveArgs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RandomPoll" eSuperTypes="#//Expression #//Poll">
    <eStructuralFeatures xsi:type="ecore:EReference" name="channel" eType="#//Reference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" eType="#//ReceiveArgs"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
