/*
 * generated by Xtext
 */
package fr.lip6.move.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class GalWebModule extends AbstractGalWebModule {
}
