/*
 * generated by Xtext
 */
package fr.lip6.move.promela.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PromelaUiModule extends fr.lip6.move.promela.ui.AbstractPromelaUiModule {
	public PromelaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
