/*
 * generated by Xtext
 */
package fr.lip6.move.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class TimedAutomataScopeProvider extends AbstractTimedAutomataScopeProvider {

}
