/*
 * generated by Xtext
 */
package fr.lip6.move.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.lip6.move.TimedAutomataRuntimeModule;
import fr.lip6.move.TimedAutomataStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TimedAutomataIdeSetup extends TimedAutomataStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TimedAutomataRuntimeModule(), new TimedAutomataIdeModule()));
	}
	
}
