/*
* generated by Xtext
*/
package fr.lip6.move.gal.ui.contentassist;

import fr.lip6.move.gal.ui.contentassist.AbstractLogicProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class LogicProposalProvider extends AbstractLogicProposalProvider {

}
