/*
* generated by Xtext
*/
package fr.lip6.move.coloane.ui.contentassist;

import fr.lip6.move.coloane.ui.contentassist.AbstractItsDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ItsDslProposalProvider extends AbstractItsDslProposalProvider {

}
