/*
 * generated by Xtext 2.33.0
 */
package fr.lip6.move;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class AhgStandaloneSetup extends AhgStandaloneSetupGenerated {

	public static void doSetup() {
		new AhgStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
