/*
 * generated by Xtext 2.33.0
 */
package fr.lip6.move;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class AHGStandaloneSetup extends AHGStandaloneSetupGenerated {

	public static void doSetup() {
		new AHGStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
