/*
 * generated by Xtext
 */
package fr.lip6.move.divine;

import org.eclipse.xtext.scoping.IScopeProvider;
import fr.lip6.move.divine.scoping.DivineScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DivineRuntimeModule extends fr.lip6.move.divine.AbstractDivineRuntimeModule {

	
	@Override
	public Class<? extends IScopeProvider> bindIScopeProvider() {
		return DivineScopeProvider.class;
	}
}
