/*
 * generated by Xtext
 */
package fr.lip6.move.generator

import fr.lip6.move.gal.System
import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.IFileSystemAccess
import org.eclipse.xtext.generator.IGenerator

class GalGenerator implements IGenerator {
	 
	
	override void doGenerate(Resource resource, IFileSystemAccess fsa) {
		
		// Gal Systems
		for (system : resource.allContents.toIterable.filter(typeof(System))){
			val sname = system.name.replace('.', '_')
			fsa.generateFile("./main/"+sname+"_main.java",
				"public class "+sname+"_main implements IGAL{}"
			)
		}
	}
	
}
