
typedef	TYPEOBJET *PObjet;

void 	DETRUIT(TYPELISTE L);
#ifdef BIGDETRUIT
void	BIGDETRUIT(TYPELISTE L);
#endif	

TYPELISTE CREER(void);

int 	TAILLE(TYPELISTE L);

int 	INDICE(TYPELISTE L,TYPEOBJET v);

void 	SUPPRIME(TYPELISTE L,int i);
#ifdef AJOUT
int 	AJOUT(TYPELISTE L,TYPEOBJET v);
#endif
void 	NOM(TYPELISTE L,int i,TYPEOBJET *v);

int 	AJOUTFIN(TYPELISTE L,TYPEOBJET v);

#ifdef INCLUSLISTE
bool	INCLUSLISTE(TYPELISTE L1,TYPELISTE L2);
bool	EGALLISTE(TYPELISTE L1,TYPELISTE L2);
#endif

#ifdef DISJOINTLISTE
bool	DISJOINTLISTE(TYPELISTE L1,TYPELISTE L2);
#endif


