/*
 * generated by Xtext
 */
package fr.lip6.move.coloane.itsdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ItsDslUiModule extends org.xtext.example.umldsl.ui.AbstractUmlDslUiModule {
	public ItsDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
