/*
 * generated by Xtext
 */
package fr.lip6.move.ui.contentassist

import fr.lip6.move.ui.contentassist.AbstractTimedAutomataProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class TimedAutomataProposalProvider extends AbstractTimedAutomataProposalProvider {
}
