/*
 * generated by Xtext
 */
package fr.lip6.move.promela.ui.contentassist

import fr.lip6.move.promela.ui.contentassist.AbstractPromelaProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class PromelaProposalProvider extends AbstractPromelaProposalProvider {
}
