/*
* generated by Xtext
*/
package fr.lip6.move.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.lip6.move.services.TimedAutomataGrammarAccess;

public class TimedAutomataParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TimedAutomataGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.lip6.move.parser.antlr.internal.InternalTimedAutomataParser createParser(XtextTokenStream stream) {
		return new fr.lip6.move.parser.antlr.internal.InternalTimedAutomataParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "XTA";
	}
	
	public TimedAutomataGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TimedAutomataGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
