/*
* generated by Xtext
*/
package fr.lip6.move.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.lip6.move.services.GalGrammarAccess;

public class GalParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private GalGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.lip6.move.parser.antlr.internal.InternalGalParser createParser(XtextTokenStream stream) {
		return new fr.lip6.move.parser.antlr.internal.InternalGalParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "PROGRAM";
	}
	
	public GalGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GalGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
