/*
* generated by Xtext
*/
package fr.lip6.move.divine;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DivineUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return fr.lip6.move.divine.ui.internal.DivineActivator.getInstance().getInjector("fr.lip6.move.divine.Divine");
	}
	
}
