((!WrapperEsclave0.req.free) && (!WrapperEsclave0.req.answer) && (WrapperEsclave0.req.cde.dest == 0) && (!WrapperEsclave0.locked || WrapperEsclave0.req.src == WrapperEsclave0.src));
(!WrapperEsclave0.req.free);
(WrapperEsclave0.req.free==0);
(!WrapperEsclave0.req.answer);
(WrapperEsclave0.req.answer==0);
(WrapperEsclave0.req.cde.dest == 0);
(!WrapperEsclave0.locked);
(WrapperEsclave0.locked==0);
(WrapperEsclave0.req.src == WrapperEsclave0.src);
(nempty(WM1_data_out));
(WrapperEsclave0@2);
