/*
 * generated by Xtext 2.33.0
 */
package fr.lip6.move.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.lip6.move.AHGRuntimeModule;
import fr.lip6.move.AHGStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class AHGIdeSetup extends AHGStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AHGRuntimeModule(), new AHGIdeModule()));
	}
	
}
