/*
 * generated by Xtext
 */
package fr.lip6.move.divine.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DivineUiModule extends fr.lip6.move.divine.ui.AbstractDivineUiModule {
	public DivineUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	
//	 public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
//			return DivineHighlightingConfiguration.class;
//		    }
}
