/*
 * generated by Xtext 2.33.0
 */
package fr.lip6.move.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class AhgProposalProvider extends AbstractAhgProposalProvider {
}
